#!/usr/bin/env bash
#### spyglass - Picamera2 MJPG Streamer
####
#### https://github.com/roamingthings/spyglass
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
